### ISSUE TITLE
liboi will not compile with Xcode 4.5

### ISSUE THREAD

**Issue by bkloppenborg** [bkloppenborg/liboi#34]
Report from Fabien.  liboi will not compile using Xcode 4.5 on Mac OS 10.7.  The version of `clang` that is shipped with Xcode does not appear to support the full `c++11` features required for liboi.

```
$ clang -v      
Apple clang version 4.1 (tags/Apple/clang-421.11.66) (based on LLVM 3.1svn)
Target: x86_64-apple-darwin11.4.2
Thread model: posix
```

Compiling with `clang --std=c++11 and --stdlib=libc++` gives:

```
[  5%] Building CXX object lib/ccoifits/src/CMakeFiles/ccoifits_static.dir/COI_ARRAY.cpp.o
In file included from /Users/fbaron/fb/liboi/lib/ccoifits/src/COI_ARRAY.cpp:8:
In file included from /Users/fbaron/fb/liboi/lib/ccoifits/src/COI_ARRAY.h:11:
/Users/fbaron/fb/liboi/lib/ccoifits/src/COI_TABLE.h:16:10: fatal error: 'array' file not found
#include <array>
         ^
1 error generated.
make[2]:  [lib/ccoifits/src/CMakeFiles/ccoifits_static.dir/COI_ARRAY.cpp.o] Error 1
make[1]:  [lib/ccoifits/src/CMakeFiles/ccoifits_static.dir/all] Error 2
make: *** [all] Error 2
```

Compiling with `clang --std=c++11 and --stdlib=libc++` gives:

```
[  1%] Building CXX object lib/gtest-1.6.0/CMakeFiles/gtest.dir/src/gtest-all.cc.o
In file included from /Users/fbaron/fb/liboi/lib/gtest-1.6.0/src/gtest-all.cc:39:
In file included from /Users/fbaron/fb/liboi/lib/gtest-1.6.0/include/gtest/gtest.h:57:
In file included from /Users/fbaron/fb/liboi/lib/gtest-1.6.0/include/gtest/internal/gtest-internal.h:40:
/Users/fbaron/fb/liboi/lib/gtest-1.6.0/include/gtest/internal/gtest-port.h:499:13: fatal error: 'tr1/tuple' file not found
#   include <tr1/tuple>  // NOLINT
            ^
1 error generated.
make[2]:  [lib/gtest-1.6.0/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
make[1]:  [lib/gtest-1.6.0/CMakeFiles/gtest.dir/all] Error 2
make: *** [all] Error 2
```
